on:
  rss:
    url:
      # Dev blog of an interesting upcoming german Minecraft server
      - https://blog.playlegend.net/rss
      # German blog about IT-Security
      - https://tarnkappe.info/feed/
      # Guides about Puppeteer and Playwright
      - https://theheadless.dev/rss.xml
      # Swift blog
      - https://swift.org/atom.xml
      # Troy Hunt's blog
      - https://feeds.feedburner.com/TroyHunt?format=xml
      # Netflix tech blog
      - https://medium.com/feed/@netflixtechblog
      # CSGO Blog
      # TODO: maybe add dedicated channel for gaming related topics
      - https://blog.counter-strike.net/index.php/feed/
      # !removed because rsshub.app is currently really flaky
      # !9/10 the pipeline failed it was because of a 502 from rsshub
      # Official telegram channel (blog and other updates)
      # - https://rsshub.app/telegram/channel/telegram
      # Pavel Durov's telegram channel
      # - https://rsshub.app/telegram/channel/durov
      # Fly.io blog
      - https://fly.io/feed.xml
      # Spotify engineering blog
      - https://engineering.atspotify.com/feed
      # Uber engineering blog
      - https://eng.uber.com/feed
    config:
      filterOutputs:
        title: 1
        link: 1
      format: |
        // extract hostname from full url
        item.hostname = new URL(item.link).hostname;
        // remove "
        // max length for slack is 151, use 140 to have space for an emoji
        item.title = item.title.split('"').join("").substring(0, 140);
        return item;
jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      # Used for debugging
      - name: Print to console
        env:
          title: ${{ on.rss.outputs.title }}
          link: ${{ on.rss.outputs.link }}
          hostname: ${{ on.rss.outputs.hostname }}
        run: |
          echo title: $title
          echo link: $link
          echo hostname: $hostname
      - name: Slack notification
        uses: Ilshidur/action-slack@2.1.0
        env:
          title: ${{ on.rss.outputs.title }}
          link: ${{ on.rss.outputs.link }}
          hostname: ${{ on.rss.outputs.hostname }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RSS_ARTICLES }}
          SLACK_CUSTOM_PAYLOAD: '{ "text": "{{ title }}", "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": ":mega: {{ title }}", "emoji": true } }, { "type": "section", "text": { "type": "mrkdwn", "text": "`{{ hostname }}` - <{{ link }}|Click here to open>" } }, { "type": "divider" } ] }'
