on:
  rss:
    url:
      # German blog about Bitcoin and other related topics
      - https://bitcoinblog.de/feed/
      # Ethereum blog
      - https://blog.ethereum.org/feed.xml
      # Bitcoin.com blog
      - https://blog.bitcoin.com/feed/
      # Bitcoin.com news
      - https://news.bitcoin.com/feed/
    config:
      filterOutputs:
        title: 1
        link: 1
      format: |
        // extract hostname from full url
        item.hostname = new URL(item.link).hostname;
        // remove "
        item.title = item.title.split('"').join("");
        return item;
jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      # Used for debugging
      - name: Print to console
        env:
          title: ${{ on.rss.outputs.title }}
          link: ${{ on.rss.outputs.link }}
          hostname: ${{ on.rss.outputs.hostname }}
        run: |
          echo title: $title
          echo link: $link
          echo hostname: $hostname
      - name: Slack notification
        uses: Ilshidur/action-slack@2.1.0
        env:
          title: ${{ on.rss.outputs.title }}
          link: ${{ on.rss.outputs.link }}
          hostname: ${{ on.rss.outputs.hostname }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RSS_CRYPTO }}
          SLACK_CUSTOM_PAYLOAD: '{ "text": "{{ title }}", "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": ":package: {{ title }}", "emoji": true } }, { "type": "section", "text": { "type": "mrkdwn", "text": "`{{ hostname }}` - <{{ link }}|Click here to open>" } }, { "type": "divider" } ] }'
